name: CI & Benchmarks

on: [push, pull_request]

jobs:
  build-bench:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest pytest-benchmark

      - name: Build & install extension
        run: |
          pip install -e .

      - name: Run benchmarks
        run: |
          pytest benchmarks \
            --benchmark-save=ci_baseline \
            --benchmark-compare=baseline \
            --benchmark-compare-fail=0.10
